export const emprestimoRelatorio = {
    situacao: {
      devolvido: 4,
      expirado: 3,
      ativo: 4,
    },
    data: '03-03-2025',
    totalQuantidadeDisponivel: 21,
    totalQuantidade: 30,
    quantidadeEmprestada: 9,
    totalMonografiasEmprestadas: 3,
    totalLivrosEmprestados: 8,
    emprestimos: [
      {
        codigo: 1,
        utente: 'A1B2C3D4',
        contacto: '912345678',
        email: 'john.doe@example.com',
        itens: [
          {
            codigo: 1,
            utente: 'A1B2C3D4',
            utente_contacto: '912345678',
            utente_email: 'john.doe@example.com',
            data_devolucao: '03-03-2024',
            data_realizacao: '01-03-2024',
            situacao: 'devolvido',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 101,
              autor: 'José Saramago',
              titulo: 'Ensaio sobre a cegueira',
              ano: 1995,
              quantidade: 4,
              quantidadeDisponivel: 2,
              estante: {
                codigo: 1,
                nome: 'Ficção',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 1',
              localizacao: {
                codigo: 1,
                designacao: 'Biblioteca Central',
              },
              localizacaoDesignacao: 'Biblioteca Central',
              tipoObra: 'Romance',
            },
          },
        ],
      },
      {
        codigo: 2,
        utente: 'E5F6G7H8',
        contacto: '912345679',
        email: 'jane.smith@example.com',
        itens: [
          {
            codigo: 2,
            utente: 'E5F6G7H8',
            utente_contacto: '912345679',
            utente_email: 'jane.smith@example.com',
            data_devolucao: '04-03-2024',
            data_realizacao: '02-03-2024',
            situacao: 'devolvido',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 102,
              autor: 'Fernando Pessoa',
              titulo: 'O Livro do Desassossego',
              ano: 1982,
              quantidade: 4,
              quantidadeDisponivel: 1,
              estante: {
                codigo: 2,
                nome: 'Poesia',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 2',
              localizacao: {
                codigo: 2,
                designacao: 'Biblioteca Regional',
              },
              localizacaoDesignacao: 'Biblioteca Regional',
              tipoObra: 'Poesia',
            },
          },
          {
            codigo: 3,
            utente: 'E5F6G7H8',
            utente_contacto: '912345679',
            utente_email: 'jane.smith@example.com',
            data_devolucao: '05-03-2024',
            data_realizacao: '03-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 102,
              autor: 'Fernando Pessoa',
              titulo: 'O Livro do Desassossego',
              ano: 1982,
              quantidade: 4,
              quantidadeDisponivel: 1,
              estante: {
                codigo: 2,
                nome: 'Poesia',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 2',
              localizacao: {
                codigo: 2,
                designacao: 'Biblioteca Regional',
              },
              localizacaoDesignacao: 'Biblioteca Regional',
              tipoObra: 'Poesia',
            },
          },
        ],
      },
      {
        codigo: 3,
        utente: 'G9H0I1J2',
        contacto: '912345680',
        email: 'michael.green@example.com',
        itens: [
          {
            codigo: 4,
            utente: 'G9H0I1J2',
            utente_contacto: '912345680',
            utente_email: 'michael.green@example.com',
            data_devolucao: '05-03-2024',
            data_realizacao: '03-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 103,
              autor: 'Carlos Ruiz Zafón',
              titulo: 'A Sombra do Vento',
              ano: 2001,
              quantidade: 5,
              quantidadeDisponivel: 3,
              estante: {
                codigo: 3,
                nome: 'Mistério',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 3',
              localizacao: {
                codigo: 3,
                designacao: 'Biblioteca Municipal',
              },
              localizacaoDesignacao: 'Biblioteca Municipal',
              tipoObra: 'Mistério',
            },
          },
          {
            codigo: 5,
            utente: 'G9H0I1J2',
            utente_contacto: '912345680',
            utente_email: 'michael.green@example.com',
            data_devolucao: '06-03-2024',
            data_realizacao: '04-03-2024',
            situacao: 'devolvido',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 103,
              autor: 'Carlos Ruiz Zafón',
              titulo: 'A Sombra do Vento',
              ano: 2001,
              quantidade: 5,
              quantidadeDisponivel: 3,
              estante: {
                codigo: 3,
                nome: 'Mistério',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 3',
              localizacao: {
                codigo: 3,
                designacao: 'Biblioteca Municipal',
              },
              localizacaoDesignacao: 'Biblioteca Municipal',
              tipoObra: 'Mistério',
            },
          },
        ],
      },
      {
        codigo: 4,
        utente: 'K3L4M5N6',
        contacto: '912345681',
        email: 'lucy.james@example.com',
        itens: [
          {
            codigo: 6,
            utente: 'K3L4M5N6',
            utente_contacto: '912345681',
            utente_email: 'lucy.james@example.com',
            data_devolucao: '06-03-2024',
            data_realizacao: '04-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 104,
              autor: 'J.K. Rowling',
              titulo: 'Harry Potter e a Pedra Filosofal',
              ano: 1997,
              quantidade: 6,
              quantidadeDisponivel: 4,
              estante: {
                codigo: 4,
                nome: 'Fantasia',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 4',
              localizacao: {
                codigo: 4,
                designacao: 'Biblioteca Infantil',
              },
              localizacaoDesignacao: 'Biblioteca Infantil',
              tipoObra: 'Fantasia',
            },
          },
        ],
      },
      {
        codigo: 5,
        utente: 'O7P8Q9R0',
        contacto: '912345682',
        email: 'paul.brown@example.com',
        itens: [
          {
            codigo: 7,
            utente: 'O7P8Q9R0',
            utente_contacto: '912345682',
            utente_email: 'paul.brown@example.com',
            data_devolucao: '07-03-2024',
            data_realizacao: '05-03-2024',
            situacao: 'expirado',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 105,
              autor: 'George Orwell',
              titulo: '1984',
              ano: 1949,
              quantidade: 3,
              quantidadeDisponivel: 1,
              estante: {
                codigo: 5,
                nome: 'Distopia',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 5',
              localizacao: {
                codigo: 5,
                designacao: 'Biblioteca Central',
              },
              localizacaoDesignacao: 'Biblioteca Central',
              tipoObra: 'Distopia',
            },
          },
        ],
      },
      {
        codigo: 6,
        utente: 'S1T2U3V4',
        contacto: '912345683',
        email: 'mary.white@example.com',
        itens: [
          {
            codigo: 8,
            utente: 'S1T2U3V4',
            utente_contacto: '912345683',
            utente_email: 'mary.white@example.com',
            data_devolucao: '08-03-2024',
            data_realizacao: '06-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 106,
              autor: 'Harper Lee',
              titulo: 'To Kill a Mockingbird',
              ano: 1960,
              quantidade: 4,
              quantidadeDisponivel: 2,
              estante: {
                codigo: 6,
                nome: 'Clássicos',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 6',
              localizacao: {
                codigo: 6,
                designacao: 'Biblioteca Regional',
              },
              localizacaoDesignacao: 'Biblioteca Regional',
              tipoObra: 'Clássico',
            },
          },
        ],
      },
  
      // New entries
      {
        codigo: 7,
        utente: 'T1U2V3W4',
        contacto: '912345684',
        email: 'alice.green@example.com',
        itens: [
          {
            codigo: 9,
            utente: 'T1U2V3W4',
            utente_contacto: '912345684',
            utente_email: 'alice.green@example.com',
            data_devolucao: '09-03-2024',
            data_realizacao: '07-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 107,
              autor: 'J.R.R. Tolkien',
              titulo: 'O Hobbit',
              ano: 1937,
              quantidade: 5,
              quantidadeDisponivel: 3,
              estante: {
                codigo: 7,
                nome: 'Fantasia',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 7',
              localizacao: {
                codigo: 7,
                designacao: 'Biblioteca Municipal',
              },
              localizacaoDesignacao: 'Biblioteca Municipal',
              tipoObra: 'Fantasia',
            },
          },
        ],
      },
      {
        codigo: 8,
        utente: 'U3V4W5X6',
        contacto: '912345685',
        email: 'bob.jones@example.com',
        itens: [
          {
            codigo: 10,
            utente: 'U3V4W5X6',
            utente_contacto: '912345685',
            utente_email: 'bob.jones@example.com',
            data_devolucao: '10-03-2024',
            data_realizacao: '08-03-2024',
            situacao: 'expirado',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 108,
              autor: 'Mark Twain',
              titulo: 'As Aventuras de Huckleberry Finn',
              ano: 1884,
              quantidade: 6,
              quantidadeDisponivel: 3,
              estante: {
                codigo: 8,
                nome: 'Aventura',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 8',
              localizacao: {
                codigo: 8,
                designacao: 'Biblioteca Regional',
              },
              localizacaoDesignacao: 'Biblioteca Regional',
              tipoObra: 'Aventura',
            },
          },
        ],
      },
      {
        codigo: 9,
        utente: 'J1K2L3M4',
        contacto: '912345686',
        email: 'olga.white@example.com',
        itens: [
          {
            codigo: 11,
            utente: 'J1K2L3M4',
            utente_contacto: '912345686',
            utente_email: 'olga.white@example.com',
            data_devolucao: '11-03-2024',
            data_realizacao: '09-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 109,
              autor: 'Leo Tolstoy',
              titulo: 'Guerra e Paz',
              ano: 1869,
              quantidade: 7,
              quantidadeDisponivel: 5,
              estante: {
                codigo: 9,
                nome: 'História',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 9',
              localizacao: {
                codigo: 9,
                designacao: 'Biblioteca Central',
              },
              localizacaoDesignacao: 'Biblioteca Central',
              tipoObra: 'História',
            },
          },
        ],
      },
      {
        codigo: 10,
        utente: 'N5O6P7Q8',
        contacto: '912345687',
        email: 'victor.black@example.com',
        itens: [
          {
            codigo: 12,
            utente: 'N5O6P7Q8',
            utente_contacto: '912345687',
            utente_email: 'victor.black@example.com',
            data_devolucao: '12-03-2024',
            data_realizacao: '10-03-2024',
            situacao: 'devolvido',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 110,
              autor: 'Herman Melville',
              titulo: 'Moby Dick',
              ano: 1851,
              quantidade: 8,
              quantidadeDisponivel: 6,
              estante: {
                codigo: 10,
                nome: 'Aventura',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 10',
              localizacao: {
                codigo: 10,
                designacao: 'Biblioteca Infantil',
              },
              localizacaoDesignacao: 'Biblioteca Infantil',
              tipoObra: 'Aventura',
            },
          },
        ],
      },
      {
        codigo: 11,
        utente: 'R9S0T1U2',
        contacto: '912345688',
        email: 'maria.green@example.com',
        itens: [
          {
            codigo: 13,
            utente: 'R9S0T1U2',
            utente_contacto: '912345688',
            utente_email: 'maria.green@example.com',
            data_devolucao: '13-03-2024',
            data_realizacao: '11-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 111,
              autor: 'Jane Austen',
              titulo: 'Orgulho e Preconceito',
              ano: 1813,
              quantidade: 9,
              quantidadeDisponivel: 7,
              estante: {
                codigo: 11,
                nome: 'Romance',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 11',
              localizacao: {
                codigo: 11,
                designacao: 'Biblioteca Regional',
              },
              localizacaoDesignacao: 'Biblioteca Regional',
              tipoObra: 'Romance',
            },
          },
        ],
      },
      {
        codigo: 12,
        utente: 'V3W4X5Y6',
        contacto: '912345689',
        email: 'andrew.white@example.com',
        itens: [
          {
            codigo: 14,
            utente: 'V3W4X5Y6',
            utente_contacto: '912345689',
            utente_email: 'andrew.white@example.com',
            data_devolucao: '14-03-2024',
            data_realizacao: '12-03-2024',
            situacao: 'expirado',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 112,
              autor: 'Charles Dickens',
              titulo: 'Oliver Twist',
              ano: 1837,
              quantidade: 6,
              quantidadeDisponivel: 4,
              estante: {
                codigo: 12,
                nome: 'Clássicos',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 12',
              localizacao: {
                codigo: 12,
                designacao: 'Biblioteca Infantil',
              },
              localizacaoDesignacao: 'Biblioteca Infantil',
              tipoObra: 'Clássico',
            },
          },
        ],
      },
      {
        codigo: 13,
        utente: 'Z0A1B2C3',
        contacto: '912345690',
        email: 'george.smith@example.com',
        itens: [
          {
            codigo: 15,
            utente: 'Z0A1B2C3',
            utente_contacto: '912345690',
            utente_email: 'george.smith@example.com',
            data_devolucao: '15-03-2024',
            data_realizacao: '13-03-2024',
            situacao: 'ativo',
            obra: {
              tipoDeObra: 'Livro',
              codigo: 113,
              autor: 'F. Scott Fitzgerald',
              titulo: 'O Grande Gatsby',
              ano: 1925,
              quantidade: 4,
              quantidadeDisponivel: 2,
              estante: {
                codigo: 13,
                nome: 'Literatura Americana',
                tipoEstante: 'Livro',
              },
              nomeEstante: 'Estante 13',
              localizacao: {
                codigo: 13,
                designacao: 'Biblioteca Central',
              },
              localizacaoDesignacao: 'Biblioteca Central',
              tipoObra: 'Literatura Americana',
            },
          },
        ],
      },
    ],
  };
  